
name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.x"
      - "master"
  push:
    branches:
      - "*.x"
      - "master"

jobs:
  static-analysis:
    name: "Static Analysis"
    uses: "greg0ire/.github/.github/workflows/static-analysis.yml@1.1.1"
